# -*- coding: utf-8 -*-
"""Titanic_kaggle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Ldfh_fqZv-0mytxOpD6oLWtlwniRxR0
"""

import numpy as np
import pandas as pd
df= pd.read_csv("train.csv")
sex=df['Sex']=np.where(df['Sex']=='female',0,1)
mean1=df['Age'].mean(axis=0)
df.Embarked[df.Embarked=='S']=1
df.Embarked[df.Embarked=='C']=2
df.Embarked[df.Embarked=='Q']=3
mean2=df['Age'].mean(axis=0)
df['Embarked'] = df['Embarked'].fillna(mean2)
df['Age'] = df['Age'].fillna(mean1)
#df['Sex']=df['sex'].map({'male':2,'female:3'})
df_new=df.drop(['Name','Cabin','Ticket'], axis=1)
x=df_new.loc[:, df_new.columns != 'Survived'].values
y=df_new['Survived'].values.reshape(-1, 1)
print(x.shape)

#for column in feature_names:
#    print (df[column].value_counts(dropna=False))

#for test set
df1= pd.read_csv("test.csv")
df1['Sex']=np.where(df1['Sex']=='female',0,1)
mean_t=df1['Age'].mean(axis=0)
df1.Embarked[df1.Embarked=='S']=1
df1.Embarked[df1.Embarked=='C']=2
df1.Embarked[df1.Embarked=='Q']=3
mean2_t=df1['Age'].mean(axis=0)
df1['Embarked'] = df1['Embarked'].fillna(mean2_t)
df1['Age'] = df1['Age'].fillna(mean_t)
#df['Sex']=df['sex'].map({'male':2,'female:3'})
df_new_t=df1.drop(['Name','Cabin','Ticket'], axis=1)
df_new_t.replace(np.nan,0)
feature_names = df_new_t.columns.tolist()

for column in feature_names:
    print(df[column].value_counts(dropna=False))

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

clean_dataset(df_new_t)

x_t=df_new_t.values
print(x_t)

y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

y_pred = logreg.predict(x_t)
print(y_pred.shape)
y_pred.dtype

Survived=list(y_pred)

PassengerId=list(df_new_t['PassengerId'])

!pip install xlsxwriter

import xlsxwriter

workbook = xlsxwriter.Workbook('Titanic.xlsx')
outsheet= workbook.add_worksheet()
outsheet.write("A1","PassengerId")
outsheet.write("B1","Survived")
for item in range(len(Survived)):
  outsheet.write(item+1,0,PassengerId[item])
  outsheet.write(item+1,1,Survived[item])
workbook.close()

"""note: after uploading this file i got """